---
language: rust
sudo: false

rust:
  - stable

os:
  - linux

matrix:
  include:
    - os: linux
      rust: 1.39.0

script:
  - cargo build --no-default-features
  - cargo test --no-default-features
  - cargo build
  - cargo test
  - cargo fmt -- --check
  - cargo clippy

notifications:
  email:
    on_success: never
