---
language: rust
sudo: false

rust:
  - stable
  - 1.20.0

os:
  - linux

script:
  - cargo build --no-default-features
  - cargo test --no-default-features
  - if [ "${TRAVIS_RUST_VERSION}" != "1.20.0" ]; then
      cargo build;
      cargo test;
    fi

notifications:
  email:
    on_success: never
